export const selectValues = {
  cap_shape: ["bell", "conical", "convex", "knobbed", "sunken", "flat"],
  cap_surface: ["fibrous", "grooves", "scaly", "smooth"],
  cap_color: [
    "brown",
    "buff",
    "cinnamon",
    "gray",
    "green",
    "pink",
    "purple",
    "red",
    "white",
    "yellow",
  ],
  bruises: ["bruises", "no"],
  odor: [
    "almond",
    "anise",
    "creosote",
    "fishy",
    "foul",
    "musty",
    "none",
    "pungent",
    "spicy",
  ],
  gill_attachment: ["attached", "descending", "free", "notched"],
  gill_spacing: ["close", "crowded", "distant"],
  gill_size: ["broad", "narrow"],
  gill_color: [
    "black",
    "brown",
    "buff",
    "chocolate",
    "gray",
    "green",
    "orange",
    "pink",
    "purple",
    "red",
    "white",
    "yellow",
  ],
  stalk_shape: ["enlarging", "tapering"],
  stalk_root: [
    "bulbous",
    "club",
    "cup",
    "equal",
    "rhizomorphs",
    "rooted",
    "missing",
  ],
  stalk_surface_above_ring: ["fibrous", "scaly", "silky", "smooth"],
  stalk_surface_below_ring: ["fibrous", "scaly", "silky", "smooth"],
  stalk_color_above_ring: [
    "brown",
    "buff",
    "cinnamon",
    "gray",
    "orange",
    "pink",
    "red",
    "white",
    "yellow",
  ],
  stalk_color_below_ring: [
    "brown",
    "buff",
    "cinnamon",
    "gray",
    "orange",
    "pink",
    "red",
    "white",
    "yellow",
  ],
  veil_type: ["partial", "universal"],
  veil_color: ["brown", "orange", "white", "yellow"],
  ring_number: ["none", "one", "two"],
  ring_type: [
    "cobwebby",
    "evanescent",
    "flaring",
    "large",
    "none",
    "pendant",
    "sheathing",
    "zone",
  ],
  spore_print_color: [
    "black",
    "brown",
    "buff",
    "chocolate",
    "green",
    "orange",
    "purple",
    "white",
    "yellow",
  ],
  population: [
    "abundant",
    "clustered",
    "numerous",
    "scattered",
    "several",
    "solitary",
  ],
  habitat: ["grasses", "leaves", "meadows", "paths", "urban", "waste", "woods"],
};

export const initialState = {
  cap_shape: "bell",
  cap_surface: "fibrous",
  cap_color: "brown",
  bruises: "bruises",
  odor: "almond",
  gill_attachment: "attached",
  gill_spacing: "close",
  gill_size: "broad",
  gill_color: "black",
  stalk_shape: "enlarging",
  stalk_root: "bulbous",
  stalk_surface_above_ring: "fibrous",
  stalk_surface_below_ring: "fibrous",
  stalk_color_above_ring: "brown",
  stalk_color_below_ring: "brown",
  veil_type: "partial",
  veil_color: "brown",
  ring_number: "none",
  ring_type: "cobwebby",
  spore_print_color: "black",
  population: "abundant",
  habitat: "grasses",
};
